### ISSUE TITLE
Issue with toulligqc_demo_data

### ISSUE THREAD

**Issue by glustein** [GenomiqueENS/toulligQC#11]
Hi GenomiqueENS/toulligQC team.

I tried to run the provided sample data with toulligQC but a get the following error:
❯ toulligqc \
    --report-name               toulligqc_demo_aata \
    --barcoding \
    --barcodes                  BC01,BC02,BC03,BC04,BC05,B0C7 \
    --telemetry-source          sequencing_telemetry.js \
    --sequencing-summary-source sequencing_summary.txt \
    --sequencing-summary-source barcoding_summary_pass.txt \
    --sequencing-summary-source barcoding_summary_fail.txt \
    --output-directory          output
output/toulligqc_demo_aata/report.html
ToulligQC version 2.2.1
* Initialize extractors
* Start Toulligqc info extractor
* End of Toulligqc info extractor (done in 0m0.00s)
* Start Sequencing telemetry extractor
* End of Sequencing telemetry extractor (done in 0m0.05s)
* Start Basecaller sequencing summary extractor
Traceback (most recent call last):
  File "/home/glustein/.local/bin/toulligqc", line 8, in <module>
    sys.exit(main())
  File "/home/glustein/.local/lib/python3.10/site-packages/toulligqc/toulligqc.py", line 342, in main
    extractor.init()
  File "/home/glustein/.local/lib/python3.10/site-packages/toulligqc/sequencing_summary_extractor.py", line 116, in init
    self.dataframe_1d['barcode_arrangement'].cat.add_categories([0, 'other barcodes', 'passes_filtering'],
  File "/home/glustein/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/glustein/.local/lib/python3.10/site-packages/pandas/core/accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/glustein/.local/lib/python3.10/site-packages/pandas/core/arrays/categorical.py", line 2717, in __init__
    self._validate(data)
  File "/home/glustein/.local/lib/python3.10/site-packages/pandas/core/arrays/categorical.py", line 2726, in _validate
    raise AttributeError("Can only use .cat accessor with a 'category' dtype")
AttributeError: Can only use .cat accessor with a 'category' dtype. Did you mean: 'at'?

I don´t understand what is happening.
Could you help me to solve this trouble?

Thanks

**Comment by jourdren** [comment]
Dear @glustein,

Thanks for reporting this issue. 

This issue occurs when multiple sequencing summary barcode files are available like in the example dataset. If you only have one sequencing summary file, ToulligQC will work fine. I've just fixed the issue with commit  238062472f5860a8a02b96968a2058c5808fa292.

I've forgotten to add the example dataset to the list of datasets for our functional tests. Now all new ToulligQC version will always work with the exanple dataset.

A new bugfix version of ToulligQC will be published tomorrow.

Best,

Laurent.
