### ISSUE TITLE
Issue with fastq extractor when basecalled with Dorado: ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by ClairePt** [GenomiqueENS/toulligQC#34]
Hello,

Whenever I try to use toulligqc on files that have been basecalled with Dorado, I get the following error: `ValueError: dictionary update sequence element #0 has length 1; 2 is required`

I have encountered no issues when using the exact same command on the same sequencing data, the only difference being that the basecall was performed with Guppy. 

Here is the exact command I use:
 `srun -p COMPUTE toulligqc --report-name TEST --fastq /home/eleonore.durand/Nanopores_set2_2024_fastq_NO_BACKUP/10_CR2_dorado_hac.fastq --html-report-path TOULLIGQC/TEST/report.html`

And here is the full error message I get:
`ToulligQC version 2.7.1
* Initialize extractors
* Start Toulligqc info extractor
* End of Toulligqc info extractor (done in 0m0.00s)
* Start fastq extractor
Traceback (most recent call last):
  File "/eep/softwares/miniconda/envs/toulligqc-2.7.1/bin/toulligqc", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/eep/softwares/miniconda/envs/toulligqc-2.7.1/lib/python3.12/site-packages/toulligqc/toulligqc.py", line 426, in main
    extractor.init()
  File "/eep/softwares/miniconda/envs/toulligqc-2.7.1/lib/python3.12/site-packages/toulligqc/fastq_extractor.py", line 60, in init
    self.dataframe_1d = self._load_fastq_data()
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/eep/softwares/miniconda/envs/toulligqc-2.7.1/lib/python3.12/site-packages/toulligqc/fastq_extractor.py", line 253, in _load_fastq_data
    run_info = self.check_fastq()
               ^^^^^^^^^^^^^^^^^^
  File "/eep/softwares/miniconda/envs/toulligqc-2.7.1/lib/python3.12/site-packages/toulligqc/fastq_extractor.py", line 360, in check_fastq
    metadata = dict(x.split("=") for x in first_line.split(" ")[1:])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 1; 2 is required
srun: error: seed: task 0: Exited with exit code 1`

I have tried several fixes, including using specifically pandas==2.1.4 and numpy==1.26.4; but I always get the same error message. 
What could I do to fix this?

Thank you for your help,

Best regards,

Claire

**Comment by alihamraoui** [comment]
Hi @ClairePt 

Sorry for the delayed answer. Could you please provide the head of your FASTQ file so I can reproduce this issue?

Best regards,
Ali

**Comment by ClairePt** [comment]
Hello @alihamraoui ,
No problem, thank you for your answer. Below is the head of one of the fastq that were basecalled using Dorado:

@429a1c46-216d-4cfd-a67f-cdcf32c77ed5	st:Z:2024-06-11T13:10:52.535+00:00	RG:Z:2712a6db1cae52ac66ba3db53192fa918793254c_dna_r10.4.1_e8.2_400bps_hac@v5.0.0	DS:Z:gpu:Quadro RTX 3000
TTTTTTTTTTTATTTTTTAGTAAAAAACGTAACATCTTGATTTCATTGATACCACATAAGTATTGAAGATCTTTATTATTACAAGAAACTCACTTCATCACATTGAGCTGACAAAATCAACAACATCAACCACATCCATGATTCTCGGTTTCGAATTCACCACTCTACAGTTCGATCTAATTTCACCTTGCTTCCCTGTTAATGGTGGAAAGGTTTCCATCCTTATCATTGCCTTAACGAACGCGTCGAAAAATTTCCCTTGACCATCAGCGTATGCCCGGACTAATGGGATAGTGTCTTTAGCATCAGGGCTTGAGAATAACTCTTGGTCGCTTTGGATAAGACCTTTGTTCTCTTTGAGAATTCACATAGTATTTGTTGTCAAAGAGTGTTGGCGTACGTAGATAAAAATGTTGCCCCAAGACACTTGGTTTCCATTACGCGGACATTGCTTTCTTAGTGTACTCGAGTATAAGGTGCTCAAGGCTTGGGTCGGGTTTACCGGTGCTACTGAAGTTGTAAAGCCGATCCATTATAAACTGACATTGGTTTTTGCCAAAGGTGTGACCACCGGAAAGAGCAACGAGATCCGAAGGAAGATCGAGTCCGACTTTTTTGAAGCTATCCTTAAGTTGTTTAAGGGTAAAGAATGGAGCTGGAAGGTTATCATTAGCAAGATCCATAAAACCTCTTAAGCTATCTCTTCTTCCACTTGGAACCATCCATGAAGGACCTCCCGCCAAAACGACAGATTCTTGAGCCGCGATTGCGAGCAAATCAGCATCCATGAAACTGTTCTCGGACATGCTTTCTCCACGGCAGCTTTCATTTCATCGATAACATCGAAACCTCGAGCCGACTTAGCGTTCCCAAACGCGTCCTTCTCCGTCCTAAACGATGTTGTGTTGTCTTAACAATATAGACGCATCACATCCATTAACGAAGCAGTCATGGAAATGAAGACGAAGGATGCTTCGCAGCGATGCGAGGGTCTGATCTCAGAGCTTTGACAATGGTTTTGGTAGCAATGTCGAAGACTTGAGGACAAGTTTTATCGTAAAAGGAAGGACTTAAGTTCAGCATGAGACAATGAGACTTGAAGAAGAATAAGAACAAATCCTAATTTTGTCAAAGAAAATGACTTTCTGATCTTGCTCTGACTCTAAGAGAATGTTTTGGTTATCGTTTAGTTTTGAGTGAGTCCCAGCAATATCAG
+
=?003<CBADH8,,,28@<))BGIKFCB+'''922022.<9=?>HPJHKGKJE::99;-'+32/'<?CCCBEDH=DFFFKEHKGINSJGSMJISRKSLJIK??=0//-00550-,-///112==FKFDEEFGGGIMJF??@JB??5335FJO;:::E@////:3112:KDFKSIFHPLGJGQNKJSGHOFBSKMHRGSIOHIM7776403;;21101/')EDDKEHJLPIKSQSKJSSKGJP=<<<@;<<DSJGGQSGGA@:EFGIG9999777800029@BDGDEHEDEFGNFFFGD>?:0/011211010==55399:>A<:77968:<CCCKGEJIMMPHIIHBC=8KGHHA@?0,+''(&&')14664459;:<??BFDA>EFEIGEDFCDCBBADCD@998+*()--'&%%&(*55?>>==?>;,//0=7?3;FIINJKRLPJIRSJSSJIHI@DEIJIGF-('')1,+.65766666>>>BG+(()=@???GC@??@<:89=63224<?CIJ@@??FLREBAA>E=:77=75435/,-+*,,-/..1<<KLISLKNLISKIHPSSNFGIKNOSKOKSSJNIJIKKIEEA<A314//-..17:9;673323:;C??AJGEIFHSCHILSLKJJIHSKIGEGIGFKIEKIMHDDFPSMKQKNSNFHGFJLLHIIEGIFGEHHOPOLLIC;;==ONKKKMIHDHF>D:IGHGHLJHHISLPFKJGFFLKSOD4271=<:<DDD***,1/.0/50'(**DEOA@?@IC655=5,)*)(''('%$$&)+03-B@=<:;>HIIIHJHHHNSKH52//9;ACBCDEDAGFG;7888,,,,BDEHGGGHQSHPE@@@CLFFGHLGLMFIL1///99<?@21113611@@6EFIRLGIFFEEGNINNKGLHK<3-'(72237=55BCBDDCLGGGHFFFEGFFGFHGJKIHGEHIJEILLKFFGFGC;:894341,,+''-6BH@@?@SJFEFDCA@-,,'''(+8=?ABSKIJHIRJSHFHJIGGFHHBCBBIGA@?@@==:33576632389IIHGGDECDIONSHMKDECHIB<22F+**+CD>>BGE111/002444348777564))0/.//83345;:220232.-*)))))'(('%$$$$-+&&&+69:-3323BBDDFFA41276<:9+++6....1/***,45348<1&&&&)*5:2267999BA870/(
@c2f2e3f7-429d-47fa-80fe-9841be2e53bf	st:Z:2024-06-11T13:10:53.366+00:00	RG:Z:2712a6db1cae52ac66ba3db53192fa918793254c_dna_r10.4.1_e8.2_400bps_hac@v5.0.0	DS:Z:gpu:Quadro RTX 3000
ATGTTGTGGTGTACTGGTTACGAGTACGTATTGCTTTGGAGCTCTCGATTCCGTGGGACGAGCTCAACAAAGCAGCCGCCCCGTCCTACCTATTTAAAGTTTGAGAATAGGTCGAGGGCGTTGCGCCCGATGCCTCTAATCATTGGCTTTACCCGATAGAACTCGCGTCCGAGCTCCAGCTATCCTGAGGGAAACTTCGGAGGAACCAGCTACTAGATGGTTCGATTAGTATTTCGCCCCTATACCCAAGTCAGACGAACGATTTGCACGTCAGTATCGCTGCGGGCCTCCACCAGAGTTTCCTCTGGCTTCGCCCCGCTCAGGCATAGTTCACCATCTTTCGGGTCCCGACAGGCATGCTCACACTCGAACCCTTCTCAGAAGATCAAGGTCGGTCGGCGGTGCACCCGCGAGGGATCCCGCCAATCAGCTTCCTTGCGCCTTACGGGTTTACTCACCCGCTGACTCGCACACATGTAGACTCCTTGGTCCGTGTTTCAAGACGGGTCGAATGGGGAGCCCACAGGCCGACGCCCGGAGCACGCAGATGCCGAGGCACGCCGTAAAGGCGCGTGCTGCAGACCACGATCACGGTAGCGACGTCTCCGCGGGCGTATGAAGAGAGCCCGGGCTTAGGCCACCACCGTAATCCGCGTCGGTCCACGTCCCCGAATCGATCGGCGGACCGGATTTCTCCGTTCCGCATCCGACCGGGACGCGTCGCGGCCCCCATCCGCTTCCCTCCCGACAATTTCAAGCACTCTTTGACTCTCTTTTCAAAGTCACTTTCATCTTTTACCTCGCGGTACTTGTTCGCTATCGGTCTCGCCCATCTAGCCTTGGACGGAATTTACCGCCCGATTGGGGCTGCATTCCCAAACAACCCGACTCGTAGACAGCGCCTCGTGATGCGACAGGGTCCAGGGCACGACGGGGCTCTCACCCTCTCTCCGGCGCCCCTTTCCAGGGAACTTGAGCCCGGTCCGTCGCTGAGGACGCTTCTCCAGACTACAATTCGAACGCCGAGGACGTCCGATTTTCAAGCTGGGCTCTTCCCGGTTCTCGCCGTTACTAAGGGAATCCTTGTTAGTTTCTTTTCCTCCGCTTGTTGATATGCTTAAACTCAGCGGGTGATCCGCCCTAGGTTTAAGCATATCAACAAGCGGAGGAAAAGAAGAACTAACAAGGATTCCCTTAGTAACGGCAAGCGGGAAGGCCCGGCTTGAAAATCGGACGTCCTCCACGTACGGAGAAGCATCCTGAGCGACGGACCGGGCTCAAGTTCCCTGGAAGGTTCGGGAGAGAGCCCGTCGTGCAAGTATCACATCACGAGGCGCTGTCTACAGTCGGGTTGTTTGGGAATGCAGCCCCAATCGGGCGTAATTCCGTGCAAAGCGGGCGAGACCGATAGCGAAGCACCGCGAGG
+
&&+-/(&%$$$&&%&&'''%$#$$%))117667;CBH1127540+)+,,1;956...09-*''*)),.7997>@@AB97789:CEJLFEFFCBCEKJSKMJICB>B><=C?D1102=@>553349,(?AEHLSIMDDEIMNJQPJGGHINIIHG(''(>>@ADJEFIGJIHINJKKLJMKIJHPKSRHGQFENFBA?<=<<BC/CAB+++-<51467?.--.7553.&&&%%%&(.22=9;7:>>?<6111D?@@DGGGHGHEHHHLBCBCC>>;<<<@DDGEABEJKHIF65())&)*365.3'(,,--5447@CFDFGGA==>GKHFGFD==>>?>?CB<=<512:5**+46=>6558NFJSIEHHEEDFKFHKEFGFFHHCA@<66:9:5,)&((%%%&&&74454//)))-/-1143-=:9:9?CFBC:7C:H<SLJFFHCD==ABDDDFJPSSRNIIRIGGMF:978**)*222333488C?88<>GEDDKIHIKHOJJ:998A:88;<<?@=;=GHEC1../A>==:;<?JDFFSEDDCABFGGCB222IIHEAA@@DA<;;;A9944430+*''(**+@5555;<9980..**,+--/8;6>8<><985411133128<<D;==BE@7:::DGKIBBBBFHOOMSJFMHFEEIIIFJEEIJKS30009888B=<<GIJNSLKEDHFEG=;99??>5KIFMJHLLKFKKII?<//-00()*8::<::;<><;723>>>AIIQSSKGSLGGGJISSLNLSKHIKHFG76:81+)()/4.(&%&.(07******56678CFIKGMMIGEJBBIFCB/,++)(+,.//%%$%%%,,,734BFHSPHJKKOLGDHFR<;;;DHFMPGF<;;=<>A?EDIJIJJNCCDFDDB878>=@@A@AASJSQNIDCBCG>666?HF6443;==<::,,,;<?@?:('(,,4429@C8DEEGGHJ@@HFGFLLORLHJIGJHLILIHPDPDI?=999:ACGEFEHE899;GIFISGEEDRIIHEEFFFHIGPQLSJJJNONRAKJINFEFHESSPNISE@@402++*((,.;;<=<>=;;>IJMIGGHKKJIF<?EDIIFDSIHH>HJHFSPISSMHISSLMIKHSLSRICBAAHLIFIHE7,970)411014'&&*,,+,25>ADHDGDCCDGAAFF==<8,1*57:;9:==@?@:8423011001///'&%&%##$'''&'+(('')./7:<<520/-,,--..-))*+(('''38::6*))+0,**('(),345769879744444337551.+&'&&(&&''($##$%*.*++((%%$$$$$$(()())(()).123.,,,0002.-.0++++120,-/0./..064433<=75458764-,&'')))&%$$##$&$$%&&%%$&()-./)((''(''&$$$(''''
@0d45b1a7-60dd-4026-a4e2-e29abf867a10	st:Z:2024-06-11T13:11:11.629+00:00	RG:Z:2712a6db1cae52ac66ba3db53192fa918793254c_dna_r10.4.1_e8.2_400bps_hac@v5.0.0	DS:Z:gpu:Quadro RTX 3000
TTTTTTTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTAAACAAATTTTGGATGATTGAAAACAGCAGAATCATTCCTATAACATTCACAATCTTTGACACCAACATTGTCTTCAACTCATCAAAGCATCGCTAAGCTCCAGACACGCCACGAAAGAAAGAGAAAAACAGATAGAAACCGTCGCGCATTAACCATCATTACTCCAACTTCTCGAGTTCTGACATCCTTTCGATGATCGCCCTTTTGCTTGTTTCTTGGAGCTCCCCAGCAGAATGAATTCATCGAGTATCAGATACACCTTTGTGGAAATTAAACACCAAATCTAGCTCACAGACATTGCTGAAGAAATGGTGTTTAATTTCCACAAGGTGTATCTGATACTCGATGAATTCTTGCTGGGGAGCTCCAAGAAACAAGCGGAGGGAGATCATCGAAAGGAATGGTTAATGCGTGCTAGTCCATCTGTTTTTCTCTTTTTCTTTCGTGGCCGTATCTGGAGCTTTAGCGATGCTTTGATGAGTTGAAGACAATGTTGGTGTCAAAGATTGTGAATGTTATAGGGAATGATTCTGCTGTTTTCAATCATCCAAAATTTGTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by alihamraoui** [comment]
Hi @ClairePt,

It seems that your FASTQ sequence name format is new—it looks like a SAM tag format. ToulligQC doesn't currently support this.

This issue will be fixed in the upcoming version 2.7.2, which will be available soon (hopefully next week).

Thanks!
Ali

**Comment by jourdren** [comment]
This bug has been fixed with pull request #59.
